### ISSUE TITLE
The bad pixel mask algorithm is flagging all the reference pixels as dead

### ISSUE THREAD

**Issue by KevinVolkSTScI** [spacetelescope/jwst_reffiles#58]
I ran the jwst_reffiles.bad_pixel_mask code on a set of NIRISS internal flat ramp slope images, and when I looked at the results I found that all the reference pixels are flagged with flag value 1024 and flag value 1 (i.e. DO_NOT_USE) in the output bad pixel mask file.  Whilst it is true that the reference pixels are dead, this should not be flagged in the bad pixel file.

**Comment by bhilbert4** [comment]
Addressed in #59. Refpix are now stripped off of the mean slope image before sending it to the dead, low QE, and open pixel searches.
