### ISSUE TITLE
Bad Pixel Mask - test hard cut option with existing code

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwst_reffiles#64]
Add an option when searching for dead pixels to use a hard cut. That is, specify an absolute signal rate threshold below which pixels are hot....

BUT WAIT:

Actually, this can be accomplished in the code as is, by using the `absolute_rate` dark search method, setting `normalization_method='none'`, and then setting `max_dead_norm_signal` equal to the hard cut level.

Check to make sure this works.

**Comment by bsunnquist** [comment]
Yep! That gives me exactly what I got doing this manually. And we are in good agreement with the UofA results (i.e. the current pipeline bpixtab):
![comparison_absolute_rate_25](https://user-images.githubusercontent.com/16088329/56985979-9a814280-6b57-11e9-825a-2f928b3d6fc9.png)

**Comment by bsunnquist** [comment]
`max_dead_norm_signal` depends on the detector, here is the list. Should we store this somewhere as a reference?
![pipeline](https://user-images.githubusercontent.com/16088329/56986109-eb913680-6b57-11e9-9173-0d1524d01e77.png)

**Comment by bhilbert4** [comment]
Excellent! I'm thinking the values above can live in an ascii file that sits inside the repo? That way regardless of who is running the code for NIRCam, they will nominally get the same results.

**Comment by bsunnquist** [comment]
Yeah sounds good, here's a text file version. Were you thinking of just storing this as a reference file in the repo (i.e. someone on nircam can look at it to know what `max_dead_norm_signal` to choose), or setting up some automated way in the code to figure it out?

[nircam_dead_thresholds.txt](https://github.com/spacetelescope/jwst_reffiles/files/3132750/nircam_dead_thresholds.txt)

**Comment by bhilbert4** [comment]
Hmm. Maybe reading the file in, identifying the value that's in the text file, and using that as the default, in such a way that the user could override with their own value if they want to?

**Comment by bsunnquist** [comment]
yeah, I think that's best. My first thought is just put the default `max_dead_norm_signal` as something nobody would ever input (e.g. 999), then use that as a way to know if someone provided their own value (if they didn't, read the reference file). But there's probably a better way - I can work on this.

**Comment by bhilbert4** [comment]
I don't think we want to blow away the defaults that are there now though, in the case of non-NIRCam runs where people just want to normalize their slope image and use the current defaults. I've been trying to come up with a way to do this, but so far all I've been able to think of involves adding a new keyword.

Keep current defaults
If nircam and normalize_method == 'none' and dead_method == 'absolute_rate': 
    if use_historical_default:
       read in file and find proper threshold
       set max_dead_norm_signal to that value
    else:
        set max_dead_norm_signal to whatever was input

Anyway, I'll leave it to you. :)

**Comment by bsunnquist** [comment]
Yeah, the only way I can think of doing it without adding another keyword is something like:
`
def find_bad_pix(..., max_dead_norm_signal=None, ...):
    if max_dead_norm_signal==None:
        if nircam:
            read in file and find threshold
        else:
            max_dead_norm_signal=0.05  #current default
`
The only problem is the default gets kind of buried in the code here, but no new keywords are added. I don't know, do you have a preference?

**Comment by bhilbert4** [comment]
That could work. But instead of burying the defaults in the code, what if we move those into `jwst_reffiles/bad_pixel_mask/default_values.py` and import them when the bad_pixel_mask code is run. So everything would look the same as you have above, except you'd have something like this.

```
from jwst_reffiles.bad_pixel_mask.default_values import ABSOLUTE_DEADPIX_THRESHOLD

def find_bad_pix(..., max_dead_norm_signal=None, ...):
    if max_dead_norm_signal==None:
        if nircam:
            read in file and find threshold
        else:
            max_dead_norm_signal=ABSOLUTE_DEADPIX_THRESHOLD

**Comment by bsunnquist** [comment]
oh yeah I like that, it makes it more obvious where the default is located. I'll go with that method.

**Comment by bsunnquist** [comment]
Addressed here https://github.com/spacetelescope/jwst_reffiles/pull/70
