### ISSUE TITLE
Bad Pixel Mask - manual flags

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwst_reffiles#66]
Certain pixels or groups of pixels on a given detector are known to be bad. Rather than tweaking an algorithm to try and get these pixels to be properly flagged, add the ability to input a list of bad pixels and a flag type/value, and have the code do the flagging.

Examples:
MIIR - first row and column should be flagged as UNRELIABLE SLOPE
NIRCAM A1 - blob of bad pixels

My first thought is that there should be a baseline set files for this that are included in the repo, so that everyone working on a given instrument will be starting from the same set of pixels.

Format suggestion of the ascii file:

Allow entries to be single indexes, or ranges

| X       | Y           | Flag  |
| ----- |:-------:| -----:|
| 1020      | 225 | Dead |
| 0     | 4:2044      |  Unreliable_slope |
| 4:2044 | 0      | Unreliable_slope|
| 540:560 | 854:874 | Dead |

@jemorrison @arminrest What do you think?

**Comment by arminrest** [comment]
This sounds good!!
